=== lgosha/ssd/ddv/win/etc/ddv.dtd
<!ELEMENT config (section+, network, servers)>
	<!ATTLIST config
		codepage	CDATA		#REQUIRED>

	<!ELEMENT section (par+)>
	<!ATTLIST section
		name		CDATA		#REQUIRED>

	<!ELEMENT par EMPTY>
	<!ATTLIST par
		name		CDATA		#REQUIRED
		value		CDATA		#REQUIRED>

	<!ELEMENT network EMPTY>
	<!ATTLIST network
		id		CDATA		#REQUIRED
		port		CDATA		#REQUIRED>

	<!ELEMENT servers (server+)>

	<!ELEMENT server EMPTY>
	<!ATTLIST server
		id		CDATA		#REQUIRED
		addr		CDATA		#REQUIRED
		port		CDATA		#REQUIRED
		caption		CDATA		#REQUIRED>

=== lgosha/ssd/ddv/lin/etc/ddv.xml
<?xml version="1.0" encoding="WINDOWS-1251" standalone="no" ?>
<!DOCTYPE config SYSTEM "ddv.dtd">
<config codepage="cp1251">

	<section name="dir">
		<par name="etc" value="etc" />
		<par name="log" value="log" />
		<par name="tmp" value="tmp" />
	</section>

	<section name="view">
		<par name="x"		value="5"	/>
		<par name="y"		value="25"	/>
		<par name="width"	value="800"	/>
		<par name="height"	value="600"	/>
	</section>

	<section name="debug">
		<par name="level" value="8"   />
		<par name="log"   value="yes" />
	</section>

	<section name="dynamic">
		<par name="update" value="1000" />
	</section>

	<network id="801" port="3727"/>

	<servers>
		<server id="101" addr="127.0.0.1" port="3725" caption="41XXX01.dac" />
		<server id="001" addr="127.0.0.1" port="3728" caption="41XXX01.dsc" />
	</servers>

</config>
